
//Product
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

// Change theme 

export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const CHANGE_THEME_FONT_FAMILY = 'CHANGE_THEME_FONT_FAMILY';
export const CHANGE_THEME_FONT_SIZE = 'CHANGE_THEME_FONT_SIZE';
