
//Product
export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

// Change theme 

export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const CHANGE_THEME_FONT_FAMILY = 'CHANGE_THEME_FONT_FAMILY';
export const CHANGE_THEME_FONT_SIZE = 'CHANGE_THEME_FONT_SIZE';

// List News 
export const GET_LIST_NEWS_REQUEST = 'GET_LIST_NEWS_REQUEST';
export const GET_LIST_NEWS_SUCCESS = 'GET_LIST_NEWS_SUCCESS';
export const GET_LIST_NEWS_FAILURE = 'GET_LIST_NEWS_FAILURE';

// List Tab Bar 
export const GET_LIST_TAB_REQUEST = 'GET_LIST_TAB_REQUEST';
export const GET_LIST_TAB_SUCCESS = 'GET_LIST_TAB_SUCCESS';
export const GET_LIST_TAB_FAILURE = 'GET_LIST_TAB_FAILURE';
